name: flask_env  # Name of your environment
channels:
  - conda-forge  # Use conda-forge for updated packages
dependencies:
  - python=3.10  # Specify your Python version
  - flask
  - flask-cors
  - flask-sqlalchemy
  - flask-mail
  - flask-jwt-extended
  - python-decouple
  - bcrypt
  - itsdangerous
  - pip
  - Werkzeug=2.2.2
  - pip:
      - jwt=1.7.1 # version 1.7.1 otherwise get error: cannot import name 'DecodeError' from 'jwt'
